In [68]:
import openpyxl
from openpyxl import Workbook

wb = Workbook()

ws = wb.active
ws.title = "Grades"

In [69]:
# Adding header
subjects = ['Math', 'Science', 'English', 'History', 'Geography', 'Art', 'Music', 'Physical Education']
ws.append(['Name', *subjects])

In [70]:
x = np.random.randn(10, 1)

x.flatten(), np.max(x, axis=-1, initial=0, keepdims=True)


(array([-1.8346006 , -0.3685844 , -0.55362199,  0.06582382, -0.64394952,
         0.72515999, -0.2271025 ,  1.84414129, -0.45066605,  0.74259457]),
 array([[0.        ],
        [0.        ],
        [0.        ],
        [0.06582382],
        [0.        ],
        [0.72515999],
        [0.        ],
        [1.84414129],
        [0.        ],
        [0.74259457]]))

In [71]:
import numpy as np

# Here we generated grades with normal distribution capped at 0 and 100 for list of subjects
# I guess it would be easier to make function for single subject and then apply it for list
# but it was interesting to figure out how to do it in vectorized manner using numpy
def generate_grades(mean, std, num_subjects, g_min=0, g_max=100):
    grades = np.random.normal(mean, std, (num_subjects, 1))
    return np.min(np.max(grades, axis=-1, initial=g_min, keepdims=True), axis=-1, initial=g_max).round().astype(int)

generate_grades(50, 100, len(subjects))

array([100,   0,   0,  41,   0,  73,  90, 100])

In [ ]:
from faker import Faker

fake = Faker()

n_students = 20
for i in range(1, n_students + 1):
    ws.append([fake.name(), *generate_grades(50, 20, len(subjects))])


In [75]:

wb.save("grades.xlsx")


In [76]:
import pandas as pd

ws_values = list(ws.values)

# Just to check generated data
df = pd.DataFrame(ws_values[1:], columns=ws_values[0])

df.head()

Name  Math  Science  English  History  Geography  Art  \
0    Teresa Hutchinson    14       52       83       61         16   50   
1         Pedro Walker    57       54       37       35         32   63   
2  Miss Shannon Morris    57       34       63       70         31   42   
3         John Simpson    61       53       55       64         61   78   
4    Charles Allen Jr.    63       82       92       31         35   50   

   Music  Physical Education  
0     44                  41  
1     85                  46  
2     43                  64  
3     63                  26  
4     55                  50

In [77]:
from string import ascii_uppercase

au = ascii_uppercase
au


'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [78]:
ws.append(['Average', *[f'=AVERAGE({au[i]}{2}:{au[i]}{n_students + 1})' for i in range(1, len(subjects) + 1)]])

In [79]:
[cell.value for cell in list(ws.rows)[-1]]

['Average',
 '=AVERAGE(B2:B21)',
 '=AVERAGE(C2:C21)',
 '=AVERAGE(D2:D21)',
 '=AVERAGE(E2:E21)',
 '=AVERAGE(F2:F21)',
 '=AVERAGE(G2:G21)',
 '=AVERAGE(H2:H21)',
 '=AVERAGE(I2:I21)']

In [80]:
wb.save("grades.xlsx")