In [8]:
import openpyxl
from openpyxl import Workbook

wb = Workbook()

ws = wb.active
ws.title = "Grades"

In [9]:
# Adding header
subjects = ['Math', 'Science', 'English', 'History', 'Geography', 'Art', 'Music', 'Physical Education']
ws.append(['Name', *subjects])

In [10]:
import numpy as np

x = np.random.randn(10, 1)
x.flatten(), np.max(x, axis=-1, initial=0, keepdims=True)


(array([-0.27431475, -0.03988255,  0.1977965 , -0.21004098,  1.31807076,
         1.62013609, -0.01014858, -0.62412356,  2.91359987,  1.4142792 ]),
 array([[0.        ],
        [0.        ],
        [0.1977965 ],
        [0.        ],
        [1.31807076],
        [1.62013609],
        [0.        ],
        [0.        ],
        [2.91359987],
        [1.4142792 ]]))

In [11]:
# Here we generated grades with normal distribution capped at 0 and 100 for list of subjects
# I guess it would be easier to make function for single subject and then apply it for list
# but it was interesting to figure out how to do it in vectorized manner using numpy
def generate_grades(mean, std, num_subjects, g_min=0, g_max=100):
    grades = np.random.normal(mean, std, (num_subjects, 1))
    return np.min(np.max(grades, axis=-1, initial=g_min, keepdims=True), axis=-1, initial=g_max).round().astype(int)

generate_grades(50, 100, len(subjects))

array([ 43,  37,  93, 100,  56,   0,   0, 100])

In [12]:
from faker import Faker

fake = Faker()

n_students = 20
for i in range(1, n_students + 1):
    ws.append([fake.name(), *generate_grades(50, 20, len(subjects))])


In [13]:

wb.save("grades.xlsx")


In [14]:
import pandas as pd

ws_values = list(ws.values)

# Just to check generated data
df = pd.DataFrame(ws_values[1:], columns=ws_values[0])

df.head()

Name  Math  Science  English  History  Geography  Art  \
0     Andrew Washington    44       39       67       53         59   38   
1      Joseph Davenport    60       59       17       98         57   36   
2  Mrs. Hannah Mitchell    60       52        7       25         34   38   
3          Joseph Smith    33       57       66       48         67   83   
4         Amanda Hoover    62        0       48       55         55   25   

   Music  Physical Education  
0      9                  24  
1     73                  68  
2     39                  32  
3     34                  63  
4     39                  73

In [15]:
from string import ascii_uppercase

au = ascii_uppercase
au


'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [16]:
ws.append(['Average', *[f'=AVERAGE({au[i]}{2}:{au[i]}{n_students + 1})' for i in range(1, len(subjects) + 1)]])

In [17]:
[cell.value for cell in list(ws.rows)[-1]]

['Average',
 '=AVERAGE(B2:B21)',
 '=AVERAGE(C2:C21)',
 '=AVERAGE(D2:D21)',
 '=AVERAGE(E2:E21)',
 '=AVERAGE(F2:F21)',
 '=AVERAGE(G2:G21)',
 '=AVERAGE(H2:H21)',
 '=AVERAGE(I2:I21)']

In [19]:
from openpyxl.styles import Font, PatternFill

header_font = Font(bold=True, color="FFFFFF")
header_fill = PatternFill(start_color="0000FF", end_color="0000FF", fill_type="solid")

for cell in ws[1]:
    cell.font = header_font
    cell.fill = header_fill


In [20]:
wb.save("grades.xlsx")