### Exercise 1


In [3]:
import numpy as np

x = np.random.rand(5, 5)
x


array([[0.80452705, 0.78311735, 0.02762256, 0.47667638, 0.757802  ],
       [0.57280419, 0.52237573, 0.13726328, 0.94635101, 0.57317493],
       [0.34957884, 0.03949292, 0.29890833, 0.31533344, 0.54559521],
       [0.8517556 , 0.65216768, 0.85109452, 0.20498837, 0.58436354],
       [0.83888608, 0.75878797, 0.13302817, 0.08615401, 0.0493053 ]])

In [9]:
x.flat[x.argmax()] = 0
x

array([[0.80452705, 0.78311735, 0.02762256, 0.47667638, 0.757802  ],
       [0.57280419, 0.52237573, 0.13726328, 0.        , 0.57317493],
       [0.34957884, 0.03949292, 0.29890833, 0.31533344, 0.54559521],
       [0.8517556 , 0.65216768, 0.85109452, 0.20498837, 0.58436354],
       [0.83888608, 0.75878797, 0.13302817, 0.08615401, 0.0493053 ]])


### Exercise 2

In [10]:
x = np.random.randint(1, 10, 5)
y = np.random.randint(1, 10, 5)

x, y

(array([2, 7, 1, 4, 3], dtype=int32), array([9, 9, 9, 6, 8], dtype=int32))

In [35]:
def f1(x, y):
    x_vals = {x[i]: i for i in range(len(x))}
    common_elements = []
    for j in range(len(y)):
        if y[j] in x_vals:
            common_elements.append(y[j])
            x_vals.pop(y[j])
    return common_elements


def f2(x, y):
    x_set = set(x)
    y_set = set(y)
    common_elements = x_set.intersection(y_set)
    return common_elements

def f3(x, y):
    return np.intersect1d(x, y)


In [34]:
%timeit f1(x, y)
%timeit f2(x, y)
%timeit f3(x, y)


5.65 ms ± 246 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
2.99 ms ± 18.4 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
423 μs ± 580 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Exercise 3


In [36]:
x = np.random.rand(10).round(2)
x

array([0.44, 0.08, 0.99, 0.83, 0.18, 0.51, 0.91, 1.  , 0.11, 0.48])

In [38]:
# ascending order
x.sort()
x


array([0.08, 0.11, 0.18, 0.44, 0.48, 0.51, 0.83, 0.91, 0.99, 1.  ])

In [39]:
# descending order
y = x[::-1]
y

array([1.  , 0.99, 0.91, 0.83, 0.51, 0.48, 0.44, 0.18, 0.11, 0.08])

### Exercise 4


In [40]:
x = np.random.randint(1, 5, (10, 4))
x

array([[3, 4, 2, 3],
       [3, 2, 4, 1],
       [4, 1, 3, 3],
       [4, 4, 4, 3],
       [1, 2, 3, 3],
       [4, 4, 1, 3],
       [1, 3, 4, 2],
       [1, 3, 2, 3],
       [3, 1, 2, 3],
       [2, 1, 3, 4]], dtype=int32)

In [43]:
rank = np.linalg.matrix_rank(x)
print(f"The rank is: {rank}")


The rank is: 4


### Exercise 5


In [51]:
x = np.ones((5, 5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])