Exercise 1. \
Create a 1D NumPy array containing numbers from 0 to 9.

In [19]:
import numpy as np

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 2. \
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [18]:
np.array([3.14, 2.17, 0, 1, 2]).astype(int)

array([3, 2, 0, 1, 2])

Exercise 3. \
Create a 3x3 NumPy array with values ranging from 1 to 9.

In [31]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Exercise 4. \
Create a 2D NumPy array of shape (4, 5) filled with random numbers.
    

In [30]:
x = np.random.random((4, 5)).round(2)
x

array([[0.77, 0.82, 0.82, 0.6 , 0.21],
       [0.38, 0.98, 0.19, 0.86, 0.83],
       [0.43, 0.58, 0.72, 0.74, 0.29],
       [0.44, 0.39, 0.39, 0.44, 0.31]])

Exercise 5. \
Select the second row from a given 2D NumPy array.

In [21]:
x[1]

array([0.62, 1.  , 0.79, 0.39, 0.91])

Exercise 6. \
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

In [23]:
y = np.arange(10)
y[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Exercise 7. \
Create a 4x4 identity matrix using NumPy.

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Exercise 8. \
Find the sum and average of a given 1D array.


In [24]:
f'Sum: {y.sum()}, Average: {y.mean()}'

'Sum: 45, Average: 4.5'

In [28]:
np.arange(20).reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Exercise 10. \
Extract all odd numbers from a given NumPy array.


In [27]:
y[1::2]

array([1, 3, 5, 7, 9])