Ex 1. \
Create a 5x5 array with random values and find the minimum and maximum values.



In [2]:
import numpy as np

x = np.random.rand(5, 5)
x

array([[0.46214679, 0.45292294, 0.23464869, 0.39258112, 0.98629841],
       [0.00121378, 0.75173258, 0.68622772, 0.42922597, 0.0204952 ],
       [0.5372953 , 0.42792706, 0.11675174, 0.56553567, 0.05952796],
       [0.26783224, 0.67627699, 0.47481997, 0.1308567 , 0.96371349],
       [0.16044791, 0.68297142, 0.34524049, 0.16739662, 0.43500909]])

In [6]:
print(f'Min: {x.min():.2f}, Max: {x.max():.2f}')


Min: 0.00, Max: 0.99


Ex 2. \
Normalize a 3x3 random matrix (subtract the mean and divide by the standard deviation of the matrix).


In [7]:
x = np.random.rand(3, 3)
x


array([[0.07653903, 0.72726583, 0.84605712],
       [0.239305  , 0.98366269, 0.67825359],
       [0.90552956, 0.76005034, 0.90471919]])

In [8]:
x - x.mean() / x.std()


array([[-2.22182159, -1.57109479, -1.4523035 ],
       [-2.05905562, -1.31469793, -1.62010704],
       [-1.39283106, -1.53831029, -1.39364143]])

Ex 3. \
Create a 1D array of 50 evenly spaced elements between 0 and 10, exclusive.



In [11]:
np.linspace(0, 10, 50)


array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

Ex 4. \
Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).


In [14]:
x = np.random.rand(5, 3)
y = np.random.rand(3, 2)
x @ y

array([[0.483127  , 0.94128345],
       [0.75308418, 1.29567529],
       [0.3511488 , 0.80175169],
       [0.34428147, 1.06452973],
       [0.47183587, 1.11462623]])

Ex 5. \
Utilize your understanding of matrix multiplication to solve this exercise. \
Create two matrices of compatible dimensions. \
Perform matrix multiplication on these matrices and display the result. \
Ensure the dimensions of the matrices allow for valid multiplication.

In [15]:
x = np.random.rand(10, 5)
y = np.random.rand(5, 2)
x @ y


array([[1.12290685, 0.75512229],
       [1.43215623, 0.84567716],
       [1.48330715, 0.90916802],
       [1.73707301, 1.45221667],
       [1.24746824, 0.79498934],
       [1.65573877, 1.12870491],
       [1.05883976, 0.65994512],
       [0.94954709, 0.63512244],
       [1.70156654, 1.40949674],
       [1.70479874, 1.39072433]])